package de.unidue.inf.is.domain;

import org.apache.commons.net.ntp.TimeStamp;

public class bewertung {
	/*CREATE TABLE bewertung (
  	beid SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	textnachricht CLOB(1M) NOT NULL,
  	erstellungsdatum timestamp NOT NULL DEFAULT CURRENT TIMESTAMP,
  	rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  	PRIMARY KEY (beid)
);*/
	public bewertung() {};
	public int getBeid() {
		return beid;
	}
	public void setBeid(int beid) {
		this.beid = beid;
	}
	public String getTextnachricht() {
		return textnachricht;
	}
	public void setTextnachricht(String textnachricht) {
		this.textnachricht = textnachricht;
	}
	public static TimeStamp getErstellungsdatum() {
		return erstellungsdatum;
	}
	public static void setErstellungsdatum(TimeStamp erstellungsdatum) {
		bewertung.erstellungsdatum = erstellungsdatum;
	}
	public int getRating() {
		return rating;
	}
	public void setRating(int rating) {
	
		this.rating = rating;
	}
	private int beid;
	private String textnachricht;
	private static TimeStamp erstellungsdatum;
	private int rating;
	

}
