package de.unidue.inf.is.domain;

public class transportmittel {
	/*
CREATE TABLE transportmittel (
  	tid SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	name VARCHAR(50) NOT NULL,
  	icon VARCHAR(50) NOT NULL,
  	PRIMARY KEY (tid)
);
*/
	
	
	public transportmittel() {};
	
	public int getTid() {
		return tid;
	}
	public void setTid(int tid) {
		this.tid = tid;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getItem() {
		return item;
	}
	public void setItem(String item) {
		this.item = item;
	}
	private int tid;
	private String name;
	private String item;

}
